### ISSUE TITLE
Vendor "Starvedia"/ All the Models couldn't save changes in text fields.

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-admin#100]

**Comment by marcoherbst** [comment]
@faisal2472  I don't understand this task. @ijunaidfarooq do you? and do you agree it is something that needs to be done ?

**Comment by ijunaidfarooq** [comment]
@marcoherbst I dont think so because these issues are only coming to the old entered models , If we add a new entry and test it it works fine in everyway.

**Comment by marcoherbst** [comment]
I still don't understand. Is this a valid issue or not? You please make a decision on it. Of course it would be necessary to be able to edit existing models.

**Comment by ijunaidfarooq** [comment]
yes it is a valid issue and i will fix it.

**Comment by ijunaidfarooq** [comment]
@faisal2472 please test it. its done

**Comment by faisal2472** [comment]
Good work Junaid.

On 1 March 2016 at 18:57, Junaid Farooq <notifications@github.com> wrote:

> @faisal2472 <https://github.com/faisal2472> please test it. its done
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-admin/issues/100#issuecomment-190732492>
> .
>



-- 
*Faisal*

Faisal@evercam.io
Cell:+923136558054
*Skype: *faisal2472
