### ISSUE TITLE
Fix tests for Travis

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-admin#107]
all the test have been passing locally but failing over travis-ci. need to fix this due to some Associations which we have for our USER/EvercamUser.

**Comment by ijunaidfarooq** [comment]
@mosic in fixing tests for TravisCI all tests locally tests are running and mostly 49 examples are passing, But on TravisCI as Travis using an SQLSchema, which I have copied from Dashboard [(Structure.sql)](https://github.com/evercam/evercam-dashboard/blob/master/db/structure.sql). So on TravisCI, the tests don't match this Schema. Do you have any opinion on this? Mostly issue came on User's table as in admin its being used as a class Name EvercamUser.

**Comment by mosic** [comment]
@ijunaidfarooq Instead of copying the schema from the dashboard, you can make a db dump using rake, either `rake db:schema:dump` or `rake db:structure:dump`. See more information here: http://guides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you

**Comment by marcoherbst** [comment]
@ijunaidfarooq where have we got to on this?

**Comment by ijunaidfarooq** [comment]
@marcoherbst copying Schema from Dashboard was equal to dump your own schema by using above commands (Admin and Dashboard using same database) which mainly not worked for me but i dumped with this command `pg_dump -s -x -O -f /home/ijunaidfarooq/evercam-admin/db/structure.sql --schema=public evercam_dev` ( this `rake db:structure:dump` actually translate into `pg_dump -s -x -O -f /home/ijunaidfarooq/evercam-admin/db/structure.sql --schema=public evercam_dev` this. )

Tests are written on Rails Level Association between users, cameras models, vendor_models. as User on admin level is being dealt with a class name `EvercamUser`. but while going live with Travis, using the Schema file. there is no presence of `EvercamUser`. same as many tests are failing online, which are passing locally on Rails level.

**Comment by azharmalik3** [comment]
@marcoherbst tests are not implemented in the admin section. I have checked all test controllers are empty.

**Comment by azharmalik3** [comment]
Completed all models tests and added archive controller test. Create an issue #423 to add other controller tests.
