### ISSUE TITLE
Snapshot Daily Report

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-admin#170]
we have done half way through it. But it needs to build up to the same extent as we have on CloudCamba.

Currently, we are getting `snapshot_count` against a camera but its 24X7 count.

Next step is to build it in a way so we can get snapshot_count for each hour.

**Comment by marcoherbst** [comment]
This issue is waiting for this one: https://github.com/evercam/evercam-media/issues/187

**Comment by marcoherbst** [comment]
@muneeb2542 @ijunaidfarooq  I'm bumping this up to a higher milestone as now that we're on Seaweed it may be suddenly more practical to implement.

NB - Please consider carefully how this report is built so that it is useful and fast.

**Comment by marcoherbst** [comment]
This isn't currently a high priority. Let's postpone it for the future.

**Comment by marcoherbst** [comment]
Closing. Not really relevant anymore
