### ISSUE TITLE
Remove Pusher

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-admin#179]
Pusher isn't actually used in `evercam-admin` app, all the references to it are only remains of the code copied from `evercam-dashboard`.

**Comment by ijunaidfarooq** [comment]
Also Remove all other irrelevant codings coming from `evercam-dashboard` which are not being used in `evercam-admin`

**Comment by ijunaidfarooq** [comment]
It's completed. anyhow I left a few files as it was, maybe in future, we may need them as enhancements 

63 Files removed
