### ISSUE TITLE
Better filters on the Duplicate Cameras report

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#206]
https://admin.evercam.io/cameras/merge

In particular, I want to be able to filter all the "online" cameras to see only them ... but, in general, I think it needs a more useful set of filters.

@ijunaidfarooq Could this be put on the top of your list? If I had this feature by lunchtime tmrw it would be useful

**Comment by ijunaidfarooq** [comment]
Yeah sure Marco :-)

**Comment by ijunaidfarooq** [comment]
Step 2: 
Add CR Status column to report. 
Considering 
e.g 5 cameras and one have cloudRecording status on/on-schedule as whole it will show Cr Status Yes

**Comment by marcoherbst** [comment]
[image: Inline images 1]

taking a LOOONG time ....

what's happening? maybe a problem due to CR ?

or because its 2 cams in same account?

m

On 12 May 2016 at 11:17, Junaid Farooq <notifications@github.com> wrote:

> Step 2:
> Add CR Status column to report.
> Considering
> e.g 5 cameras and one have cloudRecording status on/on-schedule as whole
> it will show Cr Status Yes
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-admin/issues/206#issuecomment-218716791>
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by ijunaidfarooq** [comment]
image isnt showing?

**Comment by vinnieq** [comment]
Merge not working for me, still loading after 5 mins .

[image: Inline images 1]


Evercam.io <http://www.evercam.io/> - Cameras Unleashed
Mobile (Irl) : +353 87 987 1869
ie.linkedin.com/in/vinniequinn
@vinniequinn  / @evrcm

**Comment by ijunaidfarooq** [comment]
has been done already
