### ISSUE TITLE
Sort by CR Duration ... "24" should be less than 7. Rename to "1" ? 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#219]
24 represents 1 day of recording. Because  it's called 24 , when I sort, it comes after 7 as it's a higher number.

Could that be dealt with? Maybe by referring to 24 as "1" ? Maybe this change needs to happen somewhere other than in the Admin area, no sure.

**Comment by ijunaidfarooq** [comment]
done
