### ISSUE TITLE
Ability to Edit CR in Admin Area.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#220]
This would be especially helpful to allow us to set Infinity recording on/off where required ... which is currently (deliberately) a hard thing to do.

Here is one way it could look:
https://editor.datatables.net/examples/inline-editing/simple

And the report I most want it done on  (though it could be done on any) is the Cloud Recording report.

**Comment by ijunaid8088** [comment]
Inline editing is a bad idea. 

The best option will be:

A column showing edit fa icon, on click, pop up the current CR settings of camera (Status, Storage Duration, Interval). And not plan text input but Select options with all possible values.

**Comment by marcoherbst** [comment]
ok, good, thanks.

**Comment by ijunaid8088** [comment]
its done.
