### ISSUE TITLE
Admins report listing admins, with ability to add new and to edit or delete.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#223]
@ijunaidfarooq could you put a time estimate on this task ?

**Comment by ijunaidfarooq** [comment]
@marcoherbst How to edit an admin? Like invoke the ability to be admin?

**Comment by marcoherbst** [comment]
change email / password / name



On 9 June 2016 at 15:57, Junaid Farooq <notifications@github.com> wrote:

> @marcoherbst <https://github.com/marcoherbst> How to edit an admin? Like
> invoke the ability to be admin?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/evercam/evercam-admin/issues/223#issuecomment-224921808>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFYx_sR556FFLcPawTb2XGsopXKnlI1pks5qKCnvgaJpZM4IyEFh>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by ijunaid8088** [comment]
v1 of admin report has been added.

Admin can be added/updated/deleted.
