### ISSUE TITLE
Ability to edit a password.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#232]
Admins can't view existing passwords, but it could/should be possible for an admin to manually change someone's password.

**Comment by muneeb2542** [comment]
@marcoherbst we are hashing passwords and this type of authentication is one way.I have tried to decrypt the encrypted password using a lot of new methods but none of them produce the required result.

What can be done is a new empty text field can be shown for the password in the change modal and you can add a new password there.What do you think?

**Comment by ijunaid8088** [comment]
its done now you can edit user passwords from admin area..

![image](https://cloud.githubusercontent.com/assets/13561999/21448973/12991290-c90a-11e6-8acd-d5a6b8bb893b.png)
