### ISSUE TITLE
admin.evercam.io/onvif

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#240]
Purpose: To query any onvif endpoint for any collection of cameras and return data in a table / csv

Design:
Filter: (as with /cameras ... let me choose owner, camera name, on/off, etc.)
Endpoint: Give me a dropdown of all the Onvif endpoints, put the common 2-3 at the top.
[GO]

Result:
A table with all the elements of the resulting XML.

Whaddyathink?

My intention is to use this info to compare how we're configuring all the construction cameras. I've described it here as a general purpose report, but if it's easier, we can build it for the specific use case of: All Cameras owned by Construction , only for Endpoints that give me info about hardware &firmware, network config, stream config and image config for primary & secondary streams. ( My hunch is that it will be easier for you to do this as a generalised tool and we can ignore the few endpoints that will inevitably fail.

**Comment by ijunaid8088** [comment]
These are all those Onvif commands which can be run by any user without any parameter (With Straight Select and Go command):

https://docs.google.com/document/d/1j48p3JelyciUf0iMqfsIBh3jPN-KKvu6FeQSJfoQ5pk/edit?usp=sharing

**Comment by ijunaid8088** [comment]
as admin going to contact evrcam-server's Onvif Client to get results. the Endpoing works as
`get "/onvif/v20/:service/:operation", ONVIFController, :invoke`

Proposed Design:
Inline : Select for **Service** , Select for **Operation** , Select for **Camera** and a buttong for go.

Operation's select should be populated on the basis of Service only,

**Comment by ijunaid8088** [comment]
As Version1 I have added JSON viewer to handle the response to ONVIF query.

In case we want to parse the data to table there could be 2 ways.

http://codepen.io/junni/pen/RKdgyy

**Comment by ijunaid8088** [comment]
v1 has been deployed. 

v2:

Select a user and then load it's all cameras for Onvif Operations.

**Comment by marcoherbst** [comment]
We'll close this ticket. I'll think a little more about v2.

This is good work, thanks.

**Comment by ijunaid8088** [comment]
Okay. :)



Regards


*Junaid Farooq*
Software Developer, Evercam.io
+92334- <+92347-8666955>6944005 | junaid@evercam.io | Evercam
<http://evercam.io/> | Skype: darulehsan1
<https://mail.google.com/mail/u/0/#>
<http://www.facebook.com/ijunaid8088>  <http://pk.linkedin.com/in/iamjunnii>
  <http://github.com/ijunaid8088>  <http://twitter.com/ijunaid8088>
