### ISSUE TITLE
Migrate to Heroku

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#284]
Consider, when doing this how you do SSL.

Currently we're paying for SSL as an extra on Dash. I think this is no longer necessary:

https://www.google.ie/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=using+free+ssl+on+heroku

**Comment by ijunaid8989** [comment]
I am closing this. as Evercam Admin is also going to Hetzner VM.

https://github.com/evercam/evercam-server/issues/674
