### ISSUE TITLE
Move from AWS to Hetzner.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#325]
Junaid, is this still an issue? If so, please add some detail as to the blocker.

**Comment by ijunaid8989** [comment]
We have evercam admin running on hetzner at https://happymin.evercam.io/users/sign_in

the only issues were on map pages when we click on the map page, It doesn't load but timed out. This was the reason we stopped.

**Comment by ijunaid8989** [comment]
Closing this. We are not doing it.
