### ISSUE TITLE
Duplicate Camera report error

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-admin#330]
When I tried to merge or delete cameras using merge report I had faced that issue.

![image](https://user-images.githubusercontent.com/13760392/29613903-78c8917c-8821-11e7-94bc-c94ed2e7f7c8.png)

Seems there is an issue when we have "null" IP  & Port.

Also there is an issue when we have >5 Duplicates.

**Comment by marcoherbst** [comment]
@ijunaid8989 update this issue please.

**Comment by ijunaid8989** [comment]
@faisal2472 this issue has been fixed.

The error was coming when you try to load cameras but the Owner to those was deleted.
