### ISSUE TITLE
Construction NVR Report

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-admin#331]
Display following information:

1) Video stream info (bitrate, fps, resolution etc)
2) Hard Drive info (Used, free etc)
3) Mac
4) NVR Info: Model and Firmware
5) VH Stream Info
6) VH Camera Info
7) Highlight firmware field green/red (older / latest).

To get stream info:
http://{camera-ip+port}/ISAPI/Streaming/channels/101

To get HDD info:
/ISAPI/ContentMgmt/record/storageMounts/101

**Comment by marcoherbst** [comment]
@azharmalik3 this task? Update issue?

**Comment by azharmalik3** [comment]
Created two admin reports [Construction NVR](https://admin.evercam.io/nvr) and [Construction NVR VH](https://admin.evercam.io/nvr/vh).

Construction NVR report shows NVR HDD, device and video info.
Construction NVR VH shows virtual host camera device and video info.

Point 7: It's difficult to identify firmware older / latest and then make green/red.
Point 8 is possible but easy to get that info.

**Comment by marcoherbst** [comment]
Re: point 7 , use this method:

If 2+ models are the same and if one of those models has a lower FW than the other, mark it red.

(understand?)

**Comment by marcoherbst** [comment]
p8 -- I'll delete that.

**Comment by marcoherbst** [comment]
I'm going to close this. It's effectively done. the p7 isn't important.
