### ISSUE TITLE
After update rails version it gives travis error. fix this

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-admin#341]
Gives undefined version column error.

```
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "version" does not exist.
```

**Comment by marcoherbst** [comment]
@affan00 if you can't do this, please assign it to the appropriate person (junaid?)

**Comment by ijunaid8989** [comment]
This issue has been fixed.
For follow up:

Steps you need to resolve this issue:

1. Clone the latest Db from Heroku to local ENV.
2. run command `rake db:structure:dump`, it will create an `sql` structure file in `db` directory.
    - Also run comamnd `rake db:schema:dump`, it will update schema.rb file
3. run command `bin/rails db:environment:set RAILS_ENV=test`
4. run comamnd `RAILS_ENV=test bundle exec rake db:test:prepare`
5. Also add (3) in .travis.yml file.
6. Commit changes.
