### ISSUE TITLE
Snapshot extractor(cloud) doesn't seems to be working fine. Fix this.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-admin#343]
At first, Scedule was coming as 

"{"Monday":["08:00-17:30"],"Tuesday":["08:00-17:30"],"Wednesday":["08:00-17:30"],"Thursday":["08:00-17:30"],"Friday":["08:00-17:30"]}"

now it's coming as 

""{\"Monday\":[\"08:00-17:30\"],\"Tuesday\":[\"08:00-17:30\"],\"Wednesday\":[\"08:00-17:30\"],\"Thursday\":[\"08:00-17:30\"],\"Friday\":[\"08:00-17:30\"],\"Saturday\":[],\"Sunday\":[]}""

**Comment by ijunaid8989** [comment]
Its done.
