### ISSUE TITLE
Get AWS CodeDeploy working ?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#35]
I'm not sure about this. Main purpose of codedeploy seems to be for when you have multiple instances, but still I'm interested to see how it works and if we like it here (Where it should be easy to implement) we can begin to use it across all instances.
@shankardevy do you have an opinion on this? Does Ansible make this irrelevant?

M

**Comment by shankardevy** [comment]
@marcoherbst Yes, ansible could do a better job but right now, I haven't been successful yet with the other ansible tasks on setting up stage. so if you need me on this, this needs to wait for few more days.

btw, how does @azharmalik3 currently deploy evercam-admin?

**Comment by marcoherbst** [comment]
I'm guessing GIT push. Which is perfectly ok for this instance. The main
reason I posted this issue was curiosity to break the ice with AWS
codedeploy.

You will observe that I'm keen to use AWS tools where possible, but not
religiously. I find them more accessible (to me) even if less powerful than
3rd party tools (Cloudwatch  v New Relic being a similar story).

M

On 2 September 2015 at 17:29, Shankar Dhanasekaran <notifications@github.com
> wrote:

> @marcoherbst <https://github.com/marcoherbst> Yes, ansible could do a
> better job but right now, I haven't been successful yet with the other
> ansible tasks on setting up stage. so if you need me on this, this needs to
> wait for few more days.
>
> btw, how does @azharmalik3 <https://github.com/azharmalik3> currently
> deploy evercam-admin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-admin/issues/35#issuecomment-137157989>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by marcoherbst** [comment]
@ijunaidfarooq  ... you seem to have a method of deploying that you are happy with. If so, then let's just close this.

**Comment by ijunaidfarooq** [comment]
I may give it a shot tomorrow IF  I found this good, will go with it.
