### ISSUE TITLE
password reset not working?

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-admin#36]
![screen shot 2015-09-02 at 9 48 01 pm](https://cloud.githubusercontent.com/assets/2011812/9637099/81f576d6-51bc-11e5-8eaf-927ded565c9d.png)

**Comment by ijunaidfarooq** [comment]
@marcoherbst this issue has been resolved, I have been deploying to AWS directly to check this issues which was in Production ENV, so by checking AWS productions logs, i figured out the issues, now its working fine.
But just to take your attention towards main issue which is , there is Mailer configuration in Evercam-Admin, so it is just redirecting user to sign in page with notification, but not sending email in actual.

**Comment by ijunaidfarooq** [comment]
@marcoherbst issue is resolved completely.
