### ISSUE TITLE
Additions to /Users report for Cleanup.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#387]
Add these filters: (to existing report)

Cameras Owned < [1]
Cameras Shared <[1]
Create Date Older than [12] Months
Last Login Older than [12] Months

And, add a “Delete” button.

Caution: Think carefully about the delete button. It should not allow deleting users who own a camera. Also, if deleting a user, it is important to think carefully about all the related data that should be deleted … i.e. all shares etc.

Ability to choose #results per page.

Multiselect for Status

**Comment by ijunaid8989** [comment]
Its done almost. I am closing this as well.
