### ISSUE TITLE
Admin > Delete Jpegs

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#409]
From this page:
https://admin.evercam.io/cameras/{xxxxx}

The ability to select a time range.  (Max 1 day).

Confirm screen to show first and last image ... maybe a bit like COMPARE.

**Comment by marcoherbst** [comment]
New suggestion for interface:

Force the admin to copy and past the URLS from the cloud recordings START image and END image

Then give a confirmation step (# images to be deleted and time range ) and then OK to delete.

**Comment by ijunaid8989** [comment]
The above suggestion seems fine. 

But after getting the range between we are going to delete a snapshot, we are going to need a new endpoint for sure in evercam server for delete jpegs with timestamps.
OR 
we can delete it through evercam admin only, direct contact to seaweedfs as evercam server doing it for deletion (clean up).

**Comment by ijunaid8989** [comment]
Its done, 

We have added a new snapshot delete endpoint, which will work between 2 dates but an hour only.
