### ISSUE TITLE
Local Extraction improvements

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#41]
- [x] If I choose "Working Hours" or "All" then show the schedule anyway so I know what I'm getting.
- [x] Clone Option - New Column
- [x] Sort by Status

**Comment by ijunaid8989** [comment]
We had 3 types of status in the Database.
1, 11, 21 for in progress.
2, 12, 22 for completed.

So I changed the query to DB, for sorting. at first, when we sort the status.. 2 and 22 are being used for the same status but in sorting 2 was top of the list and 22 was down somewhere.

So now I changed the query to handle sort with a case.

```
  defp sorting("status", order) do
    "order by case
        when se.status in (2, 12, 22) then 1
        when se.status in (1, 11, 21) then 2
        else 3
      end #{order}
    "
  end
```

FYI

**Comment by ijunaid8989** [comment]
its all done.
