### ISSUE TITLE
Duplicate Cameras Report & Merge

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#42]
- [ ] New Report which shows only cameras with same IP & port.
- [ ] Checkbox to select & merge. Will then need a dialog to choose the "Merge into" account with checkboxes to merge recordings, shares, permissions ... what else?

Put  this report below "Cameras" in the navigation.

**Comment by marcoherbst** [comment]
@azharmalik3  , pass this on to someone else, if you think you can.

**Comment by ijunaidfarooq** [comment]
its done
