### ISSUE TITLE
Vendor / Model ID should not accept space or  ' . ' & Capital letter.

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-admin#44]
@muneeb2542  last few days i am working on vendor / model adding task 
I am added a lot of camera. but some model mention you at bottom of comment 
added these model with ( . ) & spaces between name that should not allowed in id.
Vendor id: icrealtime
Models:
1- icip-d1300-2.8
2- icip-d2000-2.8
3- icip-d2010-ir-d 2.8 
4- icip-d3000-2.8      
5- icip-d4002-ir-2.8   
6- maip-d2000-2.8-s
7- maip-d2000-2.8-w

**Comment by marcoherbst** [comment]
@faisal2472  ... well done for opening this issue. Could you include more info about what triggered the issue for you.

Also, I suspect the solution is more about "Do not allow vendor / model IDs that include "." or spaces. " (You've phrased it as if we should allow them.

When you've done that, you could assign the task to Muneeb.

Tks.

M

**Comment by ijunaidfarooq** [comment]
@marcoherbst this issue is resolved!

**Comment by faisal2472** [comment]
Today i was added new models under zmodo vendor.
I have found new bug, when i was added new model than it would allow to me save with capital letters.

**Comment by ijunaidfarooq** [comment]
resolved!
