### ISSUE TITLE
Y-Cam models name from capital latter not changed 

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-admin#46]

**Comment by faisal2472** [comment]
When i am trying to change name with small latter after click on save bottom refresh the page. name couldn't be change.

**Comment by ijunaidfarooq** [comment]
@marcoherbst this issues was only examined over Y-cam models, as per my discussion with @faisal2472 , he is saying we have deleted all CAPITAL letter Y-cam models and have added with small as well, Your acknowledgment needed over this issue to go on with it.

**Comment by marcoherbst** [comment]
Good, well done.

This task is closed. @faisal2472  can continue here: https://github.com/evercam/vendors-model-data/issues/2
