### ISSUE TITLE
handle search operations with Vuex instead of vue events.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-admin#49]
Sometimes while searching and typing quite fast. the Vue events lost the connection between the mounting method and clear the search query.

we are using VueEvents for now to send search Keyup events.

Replace it will vuex for better emitting

**Comment by marcoherbst** [comment]
@ijunaid8989  ... are you at a dead-end? If so, add relevant comments please.

**Comment by ijunaid8989** [comment]
For more details : https://github.com/ratiw/vuetable-2/issues/618

**Comment by ijunaid8989** [comment]
The author is keen to see a live example of that issue. But I haven't gone to that road yet or not sure if should create a live example or not.

**Comment by ijunaid8989** [comment]
relevant https://alligator.io/vuejs/lodash-throttle-debounce/

**Comment by ijunaid8989** [comment]
I have added debouncing on user filer, the idea of loadash debounce is to let you use key up and change methods but not fire the request on each change but the last change when you stop using key up or change after a specific timeout.

Right now the issue is that. when you type on keyup frequently, the state of Vue Table gets lost. and filtered data get removed and get back to the old state.

Debounce will not fire each request but let you type.. hold on all requests and fire the last one on which you get to settle for half of a second..

That's a test, for now, The Author of  VueTable suggesting to use this concept for testing.

**Comment by ijunaid8989** [comment]
It's fixed now. I am closing the issue for now. Debouncing from lodash helped us in it.
