### ISSUE TITLE
Add new camera model Ycam BLACK

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-admin#49]
Snapshot:```/snapshot.jpg```
RTSP:rtsp:```/live_mpeg4.sdp```

**Comment by marcoherbst** [comment]
But, @faisal2472 , as you know, chill out on the capital letters. The model name should just be "Black".

**Comment by faisal2472** [comment]
Just Black ? 
this model not exist 
But Black s / Black s 2 these are existing
