### ISSUE TITLE
users search filters are not usable at lower resolutions

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#50]
put all the uncommon ones into an "advanced" section

**Comment by marcoherbst** [comment]
@ijunaid8989

**Comment by marcoherbst** [comment]
half-solved. It's still not working responsively. 
Moving to milestone3 (less urgent)

**Comment by marcoherbst** [comment]
This is still bad and needs to be fixed.
![image](https://user-images.githubusercontent.com/5648894/57385005-8073df80-71a9-11e9-8d4e-c1f586682537.png)

**Comment by marcoherbst** [comment]
Upgrading to Milestone 2

**Comment by ijunaid8989** [comment]
![image](https://user-images.githubusercontent.com/13561999/57685379-2ebbd100-7651-11e9-891a-0e949dd22bd7.png)
