### ISSUE TITLE
Snapshots report

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#51]
These columns:

Name | Owner | Count  | Oldest Snapshot | CR Status | CR Duration  | CR Interval  | CR Schedule HPW | New in last 60min |

(hpw = Hours per week)

**Comment by azharmalik3** [comment]
@marcoherbst snapshot report deployed. 

All data bind except snapshot because it halt system when get snapshot count and first last snapshot.

**Comment by marcoherbst** [comment]
Perfect, thanks Azhar.

I'm reassigning this to @mosic as he is the most recent person to look at our snapshots table. Milos, I'd like to hear your approach.

@azharmalik3 if you have some specifics on things you've tried that didn't work, this would be a good time to share that info with Milos.

M
