### ISSUE TITLE
scrollbar width issue.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-admin#52]
![image](https://user-images.githubusercontent.com/13561999/56636490-64891d80-6682-11e9-819a-1a2d71b803c3.png)
![image](https://user-images.githubusercontent.com/13561999/56636500-6d79ef00-6682-11e9-8602-6b897b22c74e.png)

**Comment by ijunaid8989** [comment]
I am changing its milestone. I have tried every possible solution on this but nothing is working for me right now.

**Comment by marcoherbst** [comment]
not important
