### ISSUE TITLE
https://admin.evercam.io/storage  new filters

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#53]
Currently, we filter by year.
I'd like a year filter "All" 
Year filter should be multi-select.

and I'd like a new multi-select that allows me to choose our Seaweed Instance ( we have 3 )

Also, put Oldest column before Newest
Make columns sortable.

**Comment by ijunaid8989** [comment]
FYI:

All the above features will require to write the report from scratch altogether.

Re: and I'd like a new multi-select that allows me to choose our Seaweed Instance ( we have 3 )
Static IP for Heroku domain unless we will not be able to request to seaweedfs filers.

Right now the report is being generated on requests to Media server for months as well as for other information. Appending information after requests to the media server breaks the column sortable part..

With all this said, I will start work on that in a bit.

**Comment by ijunaid8989** [comment]
I have tried to find static IP plan for admin but I couldn't find one, The only solution I got for this to create an endpoint over evercam server, It will be a single endpoint accepting all seaweedfs direct requests including the year and seaweedfs instance, I have discussed it with Sir Azhar and He agreed to that.

**Comment by ijunaid8989** [comment]
its done.
