### ISSUE TITLE
Delete Recordings Feature

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#64]
A mechanism to delete up to 1hr of footage.
I suggest this is in the /cloud-recordings area
When I click on Edit, let's have 2 tabs. 1 for Edit and 1 for Delete Recordings
You could use something like this interface:  https://timelapse.evercam.io/create_v2
Open to better suggestions.

**Comment by ijunaid8989** [comment]
1. Go to https://admin.evercam.io/cloud_recordings
2. Click on Edit icon.
3. Select Delete tab
4. Add Start URL i.e https://dash.evercam.io/v2/cameras/everc-fhlcr/recordings/snapshots/2019-07-06T06:01:30+05:00

From which you want to delete the images.
5. Add End URL i.e https://dash.evercam.io/v2/cameras/everc-fhlcr/recordings/snapshots/2019-07-06T06:33:30+05:00

To which you want to delete the images.

Press delete button.

**Comment by ijunaid8989** [comment]
Its done.
