### ISSUE TITLE
Move all API request operation to one module with Axios.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-admin#75]
Right we are using Axios and at someplace Vue HTTP resource.

The task is to switch to One package. Axios is a better choice. and move all API operations to one file `api.js` and use it as ES6 format such as

```
import * as API from "./api.js"
```

And make all the API operations start with `API`. It's just some code clean up and codes readability.. *Long finger.*

**Comment by marcoherbst** [comment]
@ijunaid8989 sounds good. Could you make a time estimate?

**Comment by ijunaid8989** [comment]
v2 or v3 is not relevant.

In last week I saw some conference, that the person presenting it, took that approach..

all API operation in one file. and then 

instead of making POST/GET/DELETE requests with full syntax on every page, just use 

API.get(params) otherwise ist always so many lines and stuff.

1 day is enough I think.

**Comment by ijunaid8989** [comment]
its done.
