### ISSUE TITLE
Snapshot Report - Changes to DB & Cron job to make this data more available.

### ISSUE THREAD

**Issue by ijunaidfarooq** [evercam/evercam-admin#88]
1. Create new table in evercam-database
	 - for saving some attributes from Snapshot DB
		 1. Camere_id, 
		 2. total snapshot_count, 
		 3. Report date
 2. Using whenever gem for cron job in Ruby
	 - Background job at 12:00 AM on every morning.
	 - AWS configuration for cronjob
 3. Showing all data on snapshot template  from New table
	 - Camera Name
	 - Exid
	 - Owner
	 - CR status
	 - Total Snapshot

**Comment by marcoherbst** [comment]
@mosic .... i get why this is proposed (so we can have nice reports showing usage per camera over time) and I think it's sensible. BUT ... I would like you to see and understand in case you have alternative ideas.

**Comment by mosic** [comment]
This seems sensible, only thing I'd add is that the database with stats can be a new one, local to evercam-admin application. (Unless we want to use this data elsewhere, then disregard my comment)

**Comment by marcoherbst** [comment]
I think it you put yourself in the mindset of Evercam-Media being
distributed over multiple machines, each dealing with specific cameras with
a DB of snapshots, logs and activities related to those cameras, you might
see the logic of having that data (GB used, snapshots stored) more local to
each machine.

This is a mindset more like Camba / Zoneminder and it seems to me to be
more the direction we should go. Each "recording server" is more autonomous
and has ever more of the camera info.

Maybe this is a mad ramble, in which case, excuse me, and we can dive into
this in more detail when it comes time to implement it.

M



On 13 January 2016 at 15:25, Miloš Mošić <notifications@github.com> wrote:

> This seems sensible, only thing I'd add is that the database with stats
> can be a new one, local to evercam-admin application. (Unless we want to
> use this data elsewhere, then disregard my comment)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-admin/issues/88#issuecomment-171329747>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
