### ISSUE TITLE
Add duplicate vendor automatically, "Vstarcam"

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-admin#89]
I was added many of Vendors in last 3 months. 
but don't know how, vendor "Vstarcam" added in database duplicate automatically.
I was discussed about this issue on last week.  

![error](https://cloud.githubusercontent.com/assets/13760392/12232769/41046726-b883-11e5-8cb3-7c3c71106dcf.jpg)

**Comment by ijunaidfarooq** [comment]
resolved and tested.
