### ISSUE TITLE
Take screenshots of every page in Cloud.Camba admin area and store these screenshots somewhere safe...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-admin#94]
We will almost certainly want to recreate some parts of it in the future and it will be nice to have these archives. NB. It must be private as it contains confidential data - use Google Drive, share with me. Understand each report as you go, ask me about ones you're not sure about (at the end).

**Comment by ijunaidfarooq** [comment]
You may email me the credentials for cloud.camba?

**Comment by ijunaidfarooq** [comment]
closing this
